---
title: "Ch2-Activity"
author: "Calunod, Carumba, Gementiza, Mingo, Yu"
date: "2026-02-25"
output: html_document
runtime: shiny
---

```{r}
set.seed(15)

eda_data = data.frame(
  StudentID = 1:120,
  StudyHours = runif(120, 1, 12),
  Attendance = runif(120, 60, 100),
  ScienceScore = round(40 + 4 * runif(120, 1, 12) + rnorm(120, 0, 8)),
  Month = rep(month.abb[1:6], each = 20)
)

head(eda_data)
```

## Interactive Visualization

```{r}
library(plotly)
plot_ly(
  eda_data,
  x = ~StudyHours,
  y = ~ScienceScore,
  type = "scatter",
  mode = "markers"
)
```

## Mini Dashboardl

```{r}
library(shiny)
library(plotly)

ui = fluidPage(
  titlePanel("EDA Dashboard"),
  plotlyOutput("scatter"),
  plotlyOutput("box")
)

server = function(input, output) {
  output$scatter = renderPlotly({
    plot_ly(eda_data,
            x = ~StudyHours,
            y = ~ScienceScore,
            type = "scatter",
            mode = "markers")
  })
  
  output$box = renderPlotly({
    plot_ly(eda_data,
            x = ~Month,
            y = ~ScienceScore,
            typpe = "box")
  })
}

shinyApp(ui, server)
```

## Geographical Mapping

```{r}
library(leaflet)

# 10°20'51.1"N 123°55'45.6"E

lat_val = 10 + (20/60) + (51.1/3600)
lng_val = 123 + (55/60) + (45.6/3600)

BALAY_NI_BOSS_E = leaflet() %>%
  addTiles() %>%
  addMarkers(
    lat = lat_val,
    lng = lng_val,
    popup = "BALAY NI BOSS E"
  )

BALAY_NI_BOSS_E

```
